### ISSUE TITLE
blank page when joining/creating room on safari mac

### ISSUE THREAD

**Issue by laralove143** [dyc3/opentogethertube#671] opened 2022-05-13 17:29 UTC
### Current Behavior

it shows a loading popup with the cancel button for a split second, then it's all empty.. it works fine on chrome on the same mac
safari
<img width="1361" alt="Screen Shot 2022-05-13 at 8 26 34 PM" src="https://user-images.githubusercontent.com/82576556/168336698-6c7c550a-1a1a-4529-8058-f0b4207568f1.png">

### Expected Behavior

it works the way it does on chrome

### Steps To Reproduce

1. open safari on a mac
2. create or join a room

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

**Comment by gianklug** [comment] 2022-05-13 17:35
Duplicate of #668.

**Comment by laralove143** [comment] 2022-05-13 17:47
that one's for mobile, this happens on desktops too

**Comment by gianklug** [comment] 2022-05-13 17:49
> that one's for mobile, this happens on desktops too

It's still the same rendering engine though. Mind sharing what errors are getting thrown in the JavaScript console in Safari? They are probaby the same ones as in #668 and will be (hopefully) fixed soon.

**Comment by dyc3** [comment] 2022-05-13 19:02
Closing as duplicate of #668

**Closed by dyc3** 2022-05-13 19:02 UTC
Labels: bug, duplicate, regression
