### ISSUE TITLE
The video will not load

### ISSUE THREAD

**Issue by Thepowerdude2022** [dyc3/opentogethertube#790] opened 2022-12-21 03:12 UTC
### Current Behavior

I play the video the the video does not appear it is just a black screen
I worked fine 3 days ago but now the screens black every time I play something

### Expected Behavior

I want it to play the video just as normal and not give me a black screen 

### Steps To Reproduce

1. Create room
2. Play a video
3. The black screen 

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

**Comment by dyc3** [comment] 2022-12-21 19:04
You need to provide an example of what you are trying to play, otherwise this is impossible to reproduce.

**Comment by dyc3** [comment] 2023-01-19 14:32
Closing because there's not enough info.

**Closed by dyc3** 2023-01-19 14:32 UTC
Labels: bug, uncomfirmed, needs-more-info
