### ISSUE TITLE
Implementing Video settings (resolution,speed)

### ISSUE THREAD

**Issue by HerbertvandeBrick** [dyc3/opentogethertube#710] opened 2022-07-23 09:21 UTC
### Is your feature request related to a problem? Please describe.

I´m always frustrated when i try to speed up the video i watch with my friends :-(

### Describe the solution you'd like

implementing the yt video settings button

### Additional context

I would like to support you with Bitcoin Lightning
Thanks for your work mate

**Comment by dyc3** [comment] 2022-07-23 12:01
duplicate of #35, #569

**Closed by dyc3** 2022-07-23 12:01 UTC
Labels: duplicate, enhancement
