### ISSUE TITLE
Guests can edit channel settings without permission

### ISSUE THREAD

**Issue by closewall** [dyc3/opentogethertube#461] opened 2021-07-03 16:07 UTC
## Current Behavior
As described in the title, guests are able to change things like Channel Name, description, visibility and queue mode.
I have made sure to turn those permissions off for all users except administrators, but when I join as a guest, I still have the power to change and save those settings.

### How To Reproduce

Turn all permissions for guests except chat off and save.
Login as a guest, be capable of changing the settings.

## Expected behavior
Guests, and every other user except administrators should not be able to change the channel settings.

## Screenshots
![sc1](https://user-images.githubusercontent.com/49519142/124360395-e0bd1980-dc6c-11eb-8308-662143ca3989.png)
![sc2](https://user-images.githubusercontent.com/49519142/124360394-de5abf80-dc6c-11eb-8bfe-c40ad3b9bd55.png)

**Comment by dyc3** [comment] 2021-07-06 13:22
Whoops, that's pretty bad. I'll try to take a look this afternoon when I get off work.

**Comment by dyc3** [comment] 2021-07-09 02:03
This is a duplicate of #431. Thanks for reminding me of this! I can't give an exact timeline for when it'll be fixed, but it'll be soon.

**Closed by dyc3** 2021-07-09 02:03 UTC
Labels: bug, regression, server
