### ISSUE TITLE
Subtitle and Quality options

### ISSUE THREAD

**Issue by xRealNeon** [dyc3/opentogethertube#694] opened 2022-07-01 20:33 UTC
### Is your feature request related to a problem? Please describe.

Can't turn off subtitles and can't turn down/up quality on YouTube.

### Describe the solution you'd like

Add buttons to toggle and choose subtitle and video quality.

**Comment by dyc3** [comment] 2022-07-01 21:31
Changing quality on YouTube is no longer possible with the iframe player. #35

YouTube captions is probably possible, dupe of #341

**Closed by dyc3** 2022-07-01 21:31 UTC
Labels: enhancement

**Comment by xRealNeon** [comment] 2022-07-01 21:32
Maybe it's possible with something like https://plyr.io/

**Comment by dyc3** [comment] 2022-07-01 21:47
Maybe. If we want to go the full custom player route instead of using these iframe players, I would rather stick with video.js because we're already using it for all the non iframe players. 

Tbh, it would be a fairly big and risky project.
